// test-devsu-angular/src/presentation/components/product-form/product-form.component.ts
import { Component, effect, inject, input, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import type { FinancialProduct } from '../../../domain/product';
import { addRevisionYear } from '../../../domain/dates';
import {
  emptyProductForm,
  getControlError,
  productDescriptionValidator,
  productFormValidator,
  productIdValidator,
  productNameValidator,
  releaseDateValidator,
  requiredField,
  revisionDateValidator,
} from '../../../application/product.validators';
import { PRODUCT_USE_CASES } from '../../di/product.tokens';
import { AlertComponent } from '../../shared/ui/alert/alert.component';
import { ButtonComponent } from '../../shared/ui/button/button.component';
import { InputFieldComponent } from '../../shared/ui/input-field/input-field.component';

@Component({
  selector: 'app-product-form',
  standalone: true,
  imports: [ReactiveFormsModule, AlertComponent, ButtonComponent, InputFieldComponent],
  template: `
    <form class="form" [formGroup]="form" (ngSubmit)="submit()" novalidate>
      @if (submitError()) {
        <app-alert [message]="submitError()!" />
      }

      <hr class="divider" />

      <div class="grid">
        <app-input-field
          label="ID"
          [control]="form.controls.id"
          [error]="fieldError('id')"
        />
        <app-input-field
          label="Nombre"
          [control]="form.controls.name"
          [error]="fieldError('name')"
        />
        <app-input-field
          label="Descripción"
          [control]="form.controls.description"
          [error]="fieldError('description')"
        />
        <app-input-field
          label="Logo"
          [control]="form.controls.logo"
          [error]="fieldError('logo')"
        />
        <app-input-field
          label="Fecha Liberación"
          type="date"
          [control]="form.controls.date_release"
          [error]="fieldError('date_release')"
        />
        <app-input-field
          label="Fecha Revisión"
          type="date"
          [control]="form.controls.date_revision"
          [error]="fieldError('date_revision')"
        />
      </div>

      <div class="actions">
        <app-button variant="outlined" type="button" (click)="cancel()">
          Cancelar
        </app-button>
        <app-button variant="secondary" type="button" (click)="resetForm()">
          Reiniciar
        </app-button>
        <app-button
          type="submit"
          [disabled]="form.invalid || form.pristine || submitting()"
        >
          {{ isEdit() ? 'Actualizar' : 'Enviar' }}
        </app-button>
      </div>
    </form>
  `,
  styles: [
    `
      .form {
        display: flex;
        flex-direction: column;
        gap: 20px;
      }

      .divider {
        border: none;
        border-top: 1px solid var(--color-border);
        margin: 0;
      }

      .grid {
        display: grid;
        grid-template-columns: repeat(2, minmax(0, 1fr));
        gap: 20px 24px;
      }

      .actions {
        display: flex;
        justify-content: center;
        gap: 16px;
        flex-wrap: wrap;
      }

      @media (max-width: 768px) {
        .grid {
          grid-template-columns: 1fr;
        }
      }
    `,
  ],
})
export class ProductFormComponent {
  readonly mode = input<'create' | 'edit'>('create');
  readonly productId = input<string | undefined>();
  readonly initialData = input<FinancialProduct | undefined>();

  private readonly fb = inject(FormBuilder);
  private readonly router = inject(Router);
  private readonly cases = inject(PRODUCT_USE_CASES);

  readonly submitError = signal<string | null>(null);
  readonly submitting = signal(false);

  readonly form = this.fb.nonNullable.group(
    {
      id: ['', [productIdValidator()]],
      name: ['', [productNameValidator()]],
      description: ['', [productDescriptionValidator()]],
      logo: ['', [requiredField()]],
      date_release: ['', [releaseDateValidator()]],
      date_revision: [{ value: '', disabled: true }, [revisionDateValidator()]],
    },
    { validators: [productFormValidator()] }
  );

  constructor() {
    effect(() => {
      this.applyInitialData();
    });

    this.form.controls.date_release.valueChanges.subscribe((releaseDate) => {
      if (!releaseDate) return;
      this.form.controls.date_revision.setValue(addRevisionYear(releaseDate));
      this.form.updateValueAndValidity();
    });

    this.form.controls.id.valueChanges.subscribe(() => {
      if (this.isEdit()) return;
      void this.verifyId();
    });
  }

  isEdit(): boolean {
    return this.mode() === 'edit';
  }

  fieldError(name: keyof typeof this.form.controls): string | null {
    const control = this.form.controls[name];
    if (name === 'date_revision' && this.form.errors?.['date_revision']) {
      if (control.dirty || control.touched || this.form.touched) {
        return String(this.form.errors['date_revision']);
      }
    }
    return getControlError(control);
  }

  async verifyId(): Promise<void> {
    const id = this.form.controls.id.value.trim();
    if (this.isEdit() || id.length < 3) return;

    const result = await this.cases.verifyProductId(id);
    if (!result.success) {
      this.form.controls.id.setErrors({ message: result.error });
      return;
    }
    if (result.value) {
      this.form.controls.id.setErrors({ message: 'ID no valido!' });
    }
  }

  async submit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.submitting.set(true);
    this.submitError.set(null);

    const raw = this.form.getRawValue();
    const product: FinancialProduct = {
      id: raw.id.trim(),
      name: raw.name.trim(),
      description: raw.description.trim(),
      logo: raw.logo.trim(),
      date_release: raw.date_release,
      date_revision: raw.date_revision,
    };

    const result =
      this.isEdit() && this.productId()
        ? await this.cases.updateProduct(this.productId()!, product)
        : await this.cases.createProduct(product);

    this.submitting.set(false);

    if (!result.success) {
      this.submitError.set(result.error);
      return;
    }

    await this.router.navigateByUrl('/');
  }

  cancel(): void {
    void this.router.navigateByUrl('/');
  }

  resetForm(): void {
    this.applyInitialData();
    this.submitError.set(null);
  }

  private applyInitialData(): void {
    const data = this.initialData() ?? emptyProductForm;
    this.form.reset(data);
    if (this.isEdit()) {
      this.form.controls.id.disable();
    } else {
      this.form.controls.id.enable();
    }
    this.form.controls.date_revision.disable();
    if (data.date_release) {
      this.form.controls.date_revision.setValue(addRevisionYear(data.date_release));
    }
  }
}

// test-devsu-react/src/presentation/components/product-form/ProductForm.tsx
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/router";
import {
  emptyProductForm,
  productFormSchema,
  type ProductFormValues,
} from "@/application/product.schema";
import type { FinancialProduct } from "@/domain/product";
import { addRevisionYear } from "@/domain/dates";
import type { ProductUseCases } from "@/application/product.use-cases";
import { Button } from "@/presentation/shared/ui/button/Button";
import { InputField } from "@/presentation/shared/ui/input-field/InputField";
import { Alert } from "@/presentation/shared/ui/alert/Alert";
import styles from "./ProductForm.module.css";

export function ProductForm({
  cases,
  mode,
  productId,
  initialData,
}: {
  cases: ProductUseCases;
  mode: "create" | "edit";
  productId?: string;
  initialData?: FinancialProduct;
}) {
  const router = useRouter();
  const isEdit = mode === "edit";
  const [submitError, setSubmitError] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    setError,
    reset,
    formState: { errors, isSubmitting, isValid, isDirty },
  } = useForm<ProductFormValues>({
    resolver: zodResolver(productFormSchema),
    defaultValues: initialData ?? emptyProductForm,
    mode: "onBlur",
  });

  const idField = register("id");
  const releaseDate = watch("date_release");

  useEffect(() => {
    if (initialData) reset(initialData);
  }, [initialData, reset]);

  useEffect(() => {
    if (releaseDate) {
      setValue("date_revision", addRevisionYear(releaseDate), { shouldValidate: true });
    }
  }, [releaseDate, setValue]);

  const verifyId = async (id: string) => {
    if (isEdit || id.length < 3) return;
    const result = await cases.verifyProductId(id.trim());
    if (!result.success) setError("id", { message: result.error });
    else if (result.value) setError("id", { message: "ID no válido!" });
  };

  const onSubmit = handleSubmit(async (values) => {
    const product: FinancialProduct = {
      id: values.id.trim(),
      name: values.name.trim(),
      description: values.description.trim(),
      logo: values.logo.trim(),
      date_release: values.date_release,
      date_revision: values.date_revision,
    };

    const result =
      isEdit && productId
        ? await cases.updateProduct(productId, product)
        : await cases.createProduct(product);

    if (!result.success) {
      setSubmitError(result.error);
      return;
    }
    await router.push("/");
  });

  return (
    <form className={styles.form} onSubmit={onSubmit} noValidate>
      {submitError ? <Alert message={submitError} /> : null}
      <hr className={styles.divider} />
      <div className={styles.grid}>
        <InputField
          label="ID"
          disabled={isEdit}
          error={errors.id?.message}
          name={idField.name}
          ref={idField.ref}
          onChange={idField.onChange}
          onBlur={(e) => {
            idField.onBlur(e);
            if (!isEdit) void verifyId(e.target.value);
          }}
        />
        <InputField label="Nombre" error={errors.name?.message} {...register("name")} />
        <InputField
          label="Descripción"
          error={errors.description?.message}
          {...register("description")}
        />
        <InputField label="Logo" error={errors.logo?.message} {...register("logo")} />
        <InputField
          label="Fecha Liberación"
          type="date"
          error={errors.date_release?.message}
          {...register("date_release")}
        />
        <InputField
          label="Fecha Revisión"
          type="date"
          disabled
          error={errors.date_revision?.message}
          {...register("date_revision")}
        />
      </div>
      <div className={styles.actions}>
        <Button
          type="button"
          variant="secondary"
          onClick={() => router.push("/")}
          style={{
            border: "1px solid #6b7280",
          }}
        >
          Cancelar
        </Button>
        <Button
          type="button"
          variant="secondary"
          onClick={() => reset(initialData ?? emptyProductForm)}
        >
          Reiniciar
        </Button>
        <Button type="submit" variant="primary" disabled={isSubmitting || !isValid || !isDirty}>
          {isEdit ? "Actualizar" : "Enviar"}
        </Button>
      </div>
    </form>
  );
}
