// test-devsu-angular/src/presentation/components/product-row-menu/product-row-menu.component.ts
import {
  Component,
  ElementRef,
  HostListener,
  inject,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import type { FinancialProduct } from '../../../domain/product';

@Component({
  selector: 'app-product-row-menu',
  standalone: true,
  template: `
    <div class="menu">
      <button
        #trigger
        type="button"
        class="trigger"
        [attr.aria-expanded]="open()"
        aria-haspopup="menu"
        (click)="toggle()"
      >
        &#8942;
      </button>
      @if (open()) {
        <div class="dropdown" [style]="menuStyle()" role="menu">
          <button type="button" role="menuitem" (click)="edit()">Editar</button>
          <button type="button" role="menuitem" class="danger" (click)="remove()">
            Eliminar
          </button>
        </div>
      }
    </div>
  `,
  styles: [
    `
      .menu {
        position: relative;
        display: inline-block;
      }

      .trigger {
        border: none;
        background: transparent;
        cursor: pointer;
        font-size: 1.25rem;
      }

      .dropdown {
        position: fixed;
        min-width: 120px;
        background: #fff;
        border: 1px solid var(--color-border);
        border-radius: var(--radius-sm);
        box-shadow: var(--shadow-card);
        z-index: 200;
      }

      .dropdown button {
        display: block;
        width: 100%;
        border: none;
        background: #fff;
        padding: 10px 12px;
        text-align: left;
        cursor: pointer;
      }

      .danger {
        color: var(--color-danger);
      }
    `,
  ],
})
export class ProductRowMenuComponent {
  readonly product = input.required<FinancialProduct>();
  readonly editProduct = output<FinancialProduct>();
  readonly deleteProduct = output<FinancialProduct>();

  private readonly host = inject(ElementRef<HTMLElement>);
  private readonly triggerRef = viewChild<ElementRef<HTMLButtonElement>>('trigger');
  readonly open = signal(false);
  readonly menuStyle = signal<Record<string, string>>({});

  toggle(): void {
    if (this.open()) {
      this.open.set(false);
      return;
    }

    const rect = this.triggerRef()?.nativeElement.getBoundingClientRect();
    if (!rect) return;

    const menuHeight = 88;
    const gap = 4;
    const openUp = rect.bottom + menuHeight > window.innerHeight && rect.top > menuHeight;

    this.menuStyle.set(
      openUp
        ? {
            top: `${rect.top - gap}px`,
            left: `${rect.right}px`,
            transform: 'translate(-100%, -100%)',
          }
        : {
            top: `${rect.bottom + gap}px`,
            left: `${rect.right}px`,
            transform: 'translateX(-100%)',
          }
    );
    this.open.set(true);
  }

  edit(): void {
    this.open.set(false);
    this.editProduct.emit(this.product());
  }

  remove(): void {
    this.open.set(false);
    this.deleteProduct.emit(this.product());
  }

  @HostListener('document:mousedown', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    if (!this.host.nativeElement.contains(event.target as Node)) {
      this.open.set(false);
    }
  }
}

// test-devsu/src/presentation/components/product-row-menu/ProductRowMenu.tsx
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
} from "react";
import { createPortal } from "react-dom";
import type { FinancialProduct } from "@/domain/product";
import styles from "./ProductRowMenu.module.css";

const MENU_HEIGHT = 88;

function getMenuStyle(rect: DOMRect): CSSProperties {
  const gap = 4;
  const openUp =
    rect.bottom + MENU_HEIGHT > window.innerHeight && rect.top > MENU_HEIGHT;

  return {
    position: "fixed",
    top: openUp ? rect.top - gap : rect.bottom + gap,
    left: rect.right,
    transform: openUp ? "translate(-100%, -100%)" : "translateX(-100%)",
  };
}

export function ProductRowMenu({
  product,
  onEdit,
  onDelete,
}: {
  product: FinancialProduct;
  onEdit: (p: FinancialProduct) => void;
  onDelete: (p: FinancialProduct) => void;
}) {
  const [open, setOpen] = useState(false);
  const [menuStyle, setMenuStyle] = useState<CSSProperties | null>(null);
  const rootRef = useRef<HTMLDivElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);

  const updatePosition = useCallback(() => {
    const rect = triggerRef.current?.getBoundingClientRect();
    if (!rect) return;
    setMenuStyle(getMenuStyle(rect));
  }, []);

  useLayoutEffect(() => {
    if (!open) {
      setMenuStyle(null);
      return;
    }
    updatePosition();
    window.addEventListener("scroll", updatePosition, true);
    window.addEventListener("resize", updatePosition);
    return () => {
      window.removeEventListener("scroll", updatePosition, true);
      window.removeEventListener("resize", updatePosition);
    };
  }, [open, updatePosition]);

  useEffect(() => {
    const close = (e: MouseEvent) => {
      const target = e.target as Node;
      if (
        rootRef.current?.contains(target) ||
        dropdownRef.current?.contains(target)
      ) {
        return;
      }
      setOpen(false);
    };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, []);

  const dropdown =
    open && menuStyle ? (
      <div ref={dropdownRef} className={styles.dropdown} style={menuStyle} role="menu">
        <button
          type="button"
          role="menuitem"
          onClick={() => {
            setOpen(false);
            onEdit(product);
          }}
        >
          Editar
        </button>
        <button
          type="button"
          role="menuitem"
          className={styles.danger}
          onClick={() => {
            setOpen(false);
            onDelete(product);
          }}
        >
          Eliminar
        </button>
      </div>
    ) : null;

  return (
    <div className={styles.menu} ref={rootRef}>
      <button
        type="button"
        ref={triggerRef}
        className={styles.trigger}
        aria-expanded={open}
        aria-haspopup="menu"
        onClick={() => setOpen((v) => !v)}
      >
        ⋮
      </button>
      {typeof document !== "undefined" && dropdown
        ? createPortal(dropdown, document.body)
        : null}
    </div>
  );
}
