// test-devsu-angular/src/presentation/components/delete-product-modal/delete-product-modal.component.ts
import { Component, input, output } from '@angular/core';
import type { FinancialProduct } from '../../../domain/product';
import { AlertComponent } from '../../shared/ui/alert/alert.component';
import { ButtonComponent } from '../../shared/ui/button/button.component';
import { ModalComponent } from '../../shared/ui/modal/modal.component';

@Component({
  selector: 'app-delete-product-modal',
  standalone: true,
  imports: [ModalComponent, AlertComponent, ButtonComponent],
  template: `
    <app-modal [open]="!!product()" (onClose)="close.emit()">
      @if (error()) {
        <app-alert [message]="error()!" />
      }
      <p class="message">
        Estas seguro de eliminar el producto <strong>{{ product()?.name }}</strong>?
      </p>
      <div modal-footer>
        <app-button variant="secondary" [disabled]="deleting()" (click)="close.emit()">
          Cancelar
        </app-button>
        <app-button variant="danger" [disabled]="deleting()" (click)="confirm.emit()">
          Confirmar
        </app-button>
      </div>
    </app-modal>
  `,
  styles: [
    `
      .message {
        margin: 0;
      }
    `,
  ],
})
export class DeleteProductModalComponent {
  readonly product = input<FinancialProduct | null>(null);
  readonly deleting = input(false);
  readonly error = input<string | null>(null);
  readonly close = output<void>();
  readonly confirm = output<void>();
}

// test-devsu-react/src/presentation/components/delete-product-modal/DeleteProductModal.tsx
import type { FinancialProduct } from "@/domain/product";
import { Alert } from "@/presentation/shared/ui/alert/Alert";
import { Button } from "@/presentation/shared/ui/button/Button";
import { Modal } from "@/presentation/shared/ui/modal/Modal";
import styles from "./DeleteProductModal.module.css";

export function DeleteProductModal({
  product,
  deleting,
  error,
  onClose,
  onConfirm,
}: {
  product: FinancialProduct | null;
  deleting: boolean;
  error: string | null;
  onClose: () => void;
  onConfirm: () => void;
}) {
  return (
    <Modal
      open={Boolean(product)}
      onClose={onClose}
      footer={
        <>
          <Button variant="secondary" onClick={onClose} disabled={deleting}>
            Cancelar
          </Button>
          <Button variant="danger" onClick={onConfirm} disabled={deleting}>
            Confirmar
          </Button>
        </>
      }
    >
      {error ? <Alert message={error} /> : null}
      <p className={styles.message}>
        ¿Estas seguro de eliminar el producto <strong>{product?.name}</strong>?
      </p>
    </Modal>
  );
}
